services:

  archivator:
    build: ./arch
    container_name: infrabox-arch
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Kyiv
      PYTHONUNBUFFERED: 1
    volumes:
      - ./arch/config:/app/config
      - ./arch/data:/app/data
      - ./log:/app/log
      - ./core/config/points.json:/app/config/points.json:ro

  arch-backend:
    build: ./arch_backend
    container_name: infrabox-arch-backend
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Kyiv
      PYTHONUNBUFFERED: 1
      ARCH_URL: http://localhost:8100
    volumes:
      - ./log:/app/log

  arch-ui:
    image: nginx:stable-alpine
    container_name: infrabox-arch-ui
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Kyiv
    volumes:
      - ./arch_ui:/usr/share/nginx/html:ro
      - ./arch_ui/nginx.conf:/etc/nginx/conf.d/default.conf:ro
