services:

  backend:
    build: ./backend
    container_name: infrabox-backend
    restart: unless-stopped
    networks:
      - infrabox-net
    environment:
      REDIS_HOST: infrabox-redis
      REDIS_PORT: 6379
    expose:
      - "8000"
    volumes:
      - ./backend:/app

  web:
    image: nginx:stable-alpine
    container_name: infrabox-web
    restart: unless-stopped
    networks:
      - infrabox-net
    ports:
      - "8080:80"
    volumes:
      - ./web/html:/usr/share/nginx/html
      - ./web/conf.d:/etc/nginx/conf.d
      - ./web/nginx.conf:/etc/nginx/nginx.conf

networks:
  infrabox-net:
    external: true