services:

  adm:
    build: ../ui/adm
    container_name: infrabox-adm
    restart: unless-stopped
    pid: "host"
    networks:
      - infrabox-net
    environment:
      HOSTNAME: infrabox-adm
      REDIS_HOST: ${REDIS_HOST:-infrabox-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      TZ: Europe/Kyiv
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
      - /home/shura/infrabox:/home/shura/infrabox:ro
      - /etc/hostname:/host_hostname:ro
      - ../ui/adm/main.py:/app/main.py
      - ./data:/app/data
      - ../core/service/config:/app/config
      - ../infrabox.json:/app/config/infrabox.json

networks:
  infrabox-net:
    external: true
