services:

  adm:
    build: ../ui/adm
    container_name: infrabox-adm
    restart: unless-stopped
    pid: "host"
    networks:
      - infrabox-net
    environment:
      HOSTNAME: infrabox-adm
      REDIS_HOST: infrabox-redis
      REDIS_PORT: 6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
      - /home/shura/infrabox:/home/shura/infrabox:ro
      - /etc/hostname:/host_hostname:ro
      - ./data:/app/data
      - ../infrabox.json:/app/config/infrabox.json
      - /home/shura/infrabox/core/service/config/points.json:/app/config/points.json
      - /home/shura/infrabox/core/service/config/objects.json:/app/config/objects.json
      - /home/shura/infrabox/core/service/config/drops.json:/app/config/drops.json
      - /home/shura/infrabox/core/service/config/systems.json:/app/config/systems.json

networks:
  infrabox-net:
    external: true
