services:

  archivator:
    build: ./archivator
    container_name: infrabox-arch
    restart: unless-stopped
    networks:
      - infrabox-net
    environment:
      TZ: Europe/Kyiv
      PYTHONUNBUFFERED: 1
    volumes:
      - ./archivator/config:/app/config
      - ./archivator/data:/app/data
      - ../log:/app/log
      - ../core/service/config/points.json:/app/config/points.json:ro

  arch-backend:
    build: ./backend
    container_name: infrabox-arch-backend
    restart: unless-stopped
    networks:
      - infrabox-net
    environment:
      TZ: Europe/Kyiv
      PYTHONUNBUFFERED: 1
      ARCH_URL: http://infrabox-arch:8100
    volumes:
      - ../log:/app/log

  arch-ui:
    image: nginx:stable-alpine
    container_name: infrabox-arch-ui
    restart: unless-stopped
    networks:
      - infrabox-net
    environment:
      TZ: Europe/Kyiv
    volumes:
      - ./ui:/usr/share/nginx/html:ro
      - ./ui/nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  infrabox-net:
    external: true
